name: 'AI Inference'
description: Generate an AI response based on a provided prompt
author: 'GitHub'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'play-circle'
  color: red

# Define your inputs here.
inputs:
  prompt:
    description: Your input description here
    required: true
    default: ''
  model:
    description: The model to use
    required: false
    default: 'gpt-4o'
  endpoint:
    description: The endpoint to use
    required: false
    default: 'https://models.github.ai/inference'
  max_tokens:
    description: The maximum number of tokens to generate
    required: false
    default: '200'

# Define your outputs here.
outputs:
  response:
    description: The response from the model

runs:
  using: node20
  main: dist/index.js
